import { Faction, Planet, System } from "./types_static";
import {
  PlanetType,
  Trait,
  Specialty,
  SystemType,
  Wormhole,
  Anomaly,
  UniqueTile,
  Expansion,
} from "./types_const";

const FactionData: Faction[] = [
  {
    factionId: 1,
    game: Expansion.BaseGame,
    name: "The Arborec",
    attributes: [],
    short: "Arborec",
  },
  {
    factionId: 2,
    game: Expansion.BaseGame,
    name: "The Barony of Letnev",
    attributes: [],
    short: "Barony",
  },
  {
    factionId: 3,
    game: Expansion.BaseGame,
    name: "The Clan of Saar",
    attributes: [],
    short: "Saar",
  },
  {
    factionId: 4,
    game: Expansion.BaseGame,
    name: "The Embers of Muaat",
    attributes: [],
    short: "Muaat",
  },
  {
    factionId: 5,
    game: Expansion.BaseGame,
    name: "The Emirates of Hacan",
    attributes: [],
    short: "Hacan",
  },
  {
    factionId: 6,
    game: Expansion.BaseGame,
    name: "The Federation of Sol",
    attributes: [],
    short: "Sol",
  },
  {
    factionId: 7,
    game: Expansion.BaseGame,
    name: "The Ghosts of Creuss",
    attributes: [],
    short: "Ghosts",
  },
  {
    factionId: 8,
    game: Expansion.BaseGame,
    name: "The L1Z1X Mindnet",
    attributes: [],
    short: "L1Z1X",
  },
  {
    factionId: 9,
    game: Expansion.BaseGame,
    name: "The Mentak Coalition",
    attributes: [],
    short: "Mentak",
  },
  {
    factionId: 10,
    game: Expansion.BaseGame,
    name: "The Naalu Collective",
    attributes: [],
    short: "Naalu",
  },
  {
    factionId: 11,
    game: Expansion.BaseGame,
    name: "The Nekro Virus",
    attributes: [],
    short: "Nekro",
  },
  {
    factionId: 12,
    game: Expansion.BaseGame,
    name: "Sardakk N’orr",
    attributes: [],
    short: "Sardakk",
  },
  {
    factionId: 13,
    game: Expansion.BaseGame,
    name: "The Universities of Jol-Nar",
    attributes: [],
    short: "Universities",
  },
  {
    factionId: 14,
    game: Expansion.BaseGame,
    name: "The Winnu",
    attributes: [],
    short: "Winnu",
  },
  {
    factionId: 15,
    game: Expansion.BaseGame,
    name: "The Xxcha Kingdom",
    attributes: [],
    short: "Xxcha",
  },
  {
    factionId: 16,
    game: Expansion.BaseGame,
    name: "The Yin Brotherhood",
    attributes: [],
    short: "Yin",
  },
  {
    factionId: 17,
    game: Expansion.BaseGame,
    name: "The Yssaril Tribes",
    attributes: [],
    short: "Yssaril",
  },
  {
    factionId: 18,
    game: Expansion.ProphecyOfKings,
    name: "The Argent Flight",
    attributes: [],
    short: "Argent",
  },
  {
    factionId: 19,
    game: Expansion.ProphecyOfKings,
    name: "The Empyrean",
    attributes: [],
    short: "Empyrean",
  },
  {
    factionId: 20,
    game: Expansion.ProphecyOfKings,
    name: "The Mahact Gene-Sorcerers",
    attributes: [],
    short: "Mahact",
  },
  {
    factionId: 21,
    game: Expansion.ProphecyOfKings,
    name: "The Naaz-Rokha Alliance",
    attributes: [],
    short: "Naaz-Rokha",
  },
  {
    factionId: 22,
    game: Expansion.ProphecyOfKings,
    name: "The Nomad",
    attributes: [],
    short: "Nomad",
  },
  {
    factionId: 23,
    game: Expansion.ProphecyOfKings,
    name: "The Titans of Ul",
    attributes: [],
    short: "Titans",
  },
  {
    factionId: 24,
    game: Expansion.ProphecyOfKings,
    name: "The Vuil'Raith Cabal",
    attributes: [],
    short: "Cabal",
  },
  {
    factionId: 25,
    game: Expansion.ProphecyOfKings,
    name: "The Council Keleres",
    attributes: [],
    short: "Keleres",
  },
];

const PlanetData: Planet[] = [
  {
    systemId: 1,
    planetId: 1,
    name: "Jord",
    resources: 4,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 2,
    planetId: 2,
    name: "Moll Primus",
    resources: 4,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 3,
    planetId: 3,
    name: "Darien",
    resources: 4,
    influence: 4,
    planetType: PlanetType.Home,
  },
  {
    systemId: 4,
    planetId: 4,
    name: "Muaat",
    resources: 4,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 5,
    planetId: 5,
    name: "Nestphar",
    resources: 3,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 6,
    planetId: 6,
    name: "[0.0.0]",
    resources: 5,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 7,
    planetId: 7,
    name: "Winnu",
    resources: 3,
    influence: 4,
    planetType: PlanetType.Home,
  },
  {
    systemId: 8,
    planetId: 8,
    name: "Mordai II",
    resources: 4,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 9,
    planetId: 9,
    name: "Maaluuk",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 9,
    planetId: 10,
    name: "Druaa",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 10,
    planetId: 11,
    name: "Arc Prime",
    resources: 4,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 10,
    planetId: 12,
    name: "Wren Terra",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 11,
    planetId: 13,
    name: "Lisis II",
    resources: 1,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 11,
    planetId: 14,
    name: "Ragh",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 12,
    planetId: 15,
    name: "Nar",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Home,
  },
  {
    systemId: 12,
    planetId: 16,
    name: "Jol",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 13,
    planetId: 17,
    name: "Tren'lak",
    resources: 1,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 13,
    planetId: 18,
    name: "Quinarra",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 14,
    planetId: 19,
    name: "Archon Ren",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Home,
  },
  {
    systemId: 14,
    planetId: 20,
    name: "Archon Tau",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 15,
    planetId: 21,
    name: "Retillion",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Home,
  },
  {
    systemId: 15,
    planetId: 22,
    name: "Shalloq",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 16,
    planetId: 23,
    name: "Arretze",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 16,
    planetId: 24,
    name: "Hercant",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 16,
    planetId: 25,
    name: "Kamdorn",
    resources: 0,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 18,
    planetId: 26,
    name: "Mecatol Rex",
    resources: 1,
    influence: 6,
    planetType: PlanetType.MecatolRex,
  },
  {
    systemId: 19,
    planetId: 27,
    name: "Wellon",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Cybernetics,
  },
  {
    systemId: 20,
    planetId: 28,
    name: "Vefut II",
    resources: 2,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 21,
    planetId: 29,
    name: "Thibah",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Propulsion,
  },
  {
    systemId: 22,
    planetId: 30,
    name: "Tar'mann",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Biotic,
  },
  {
    systemId: 23,
    planetId: 31,
    name: "Saudor",
    resources: 2,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 24,
    planetId: 32,
    name: "Mehar Xull",
    resources: 1,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
    specialty: Specialty.Warfare,
  },
  {
    systemId: 25,
    planetId: 33,
    name: "Quann",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 26,
    planetId: 34,
    name: "Lodor",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 27,
    planetId: 35,
    name: "New Albion",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Biotic,
  },
  {
    systemId: 27,
    planetId: 36,
    name: "Starpoint",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 28,
    planetId: 37,
    name: "Tequ'ran",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 28,
    planetId: 38,
    name: "Torkan",
    resources: 0,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 29,
    planetId: 39,
    name: "Qucen'n",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 29,
    planetId: 40,
    name: "Rarron",
    resources: 0,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 30,
    planetId: 41,
    name: "Mellon",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 30,
    planetId: 42,
    name: "Zohbat",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 31,
    planetId: 43,
    name: "Lazar",
    resources: 1,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Cybernetics,
  },
  {
    systemId: 31,
    planetId: 44,
    name: "Sakulag",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 32,
    planetId: 45,
    name: "Dal Bootha",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 32,
    planetId: 46,
    name: "Xxehan",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 33,
    planetId: 47,
    name: "Corneeq",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 33,
    planetId: 48,
    name: "Resculon",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 34,
    planetId: 49,
    name: "Centauri",
    resources: 1,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 34,
    planetId: 50,
    name: "Gral",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Propulsion,
  },
  {
    systemId: 35,
    planetId: 51,
    name: "Bereg",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 35,
    planetId: 52,
    name: "Lirta IV",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 36,
    planetId: 53,
    name: "Arnor",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 36,
    planetId: 54,
    name: "Lor",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 37,
    planetId: 55,
    name: "Arinam",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 37,
    planetId: 56,
    name: "Meer",
    resources: 0,
    influence: 4,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
    specialty: Specialty.Warfare,
  },
  {
    systemId: 38,
    planetId: 57,
    name: "Abyz",
    resources: 3,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 38,
    planetId: 58,
    name: "Fria",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 51,
    planetId: 59,
    name: "Creuss",
    resources: 4,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 52,
    planetId: 60,
    name: "Ixth",
    resources: 3,
    influence: 5,
    planetType: PlanetType.Home,
  },
  {
    systemId: 53,
    planetId: 61,
    name: "Arcturus",
    resources: 4,
    influence: 4,
    planetType: PlanetType.Home,
  },
  {
    systemId: 54,
    planetId: 62,
    name: "Acheron",
    resources: 4,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 55,
    planetId: 63,
    name: "Elysium",
    resources: 4,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 56,
    planetId: 64,
    name: "The Dark",
    resources: 3,
    influence: 4,
    planetType: PlanetType.Home,
  },
  {
    systemId: 57,
    planetId: 65,
    name: "Naazir",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 57,
    planetId: 66,
    name: "Rokha",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 58,
    planetId: 67,
    name: "Valk",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Home,
  },
  {
    systemId: 58,
    planetId: 68,
    name: "Avar",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Home,
  },
  {
    systemId: 58,
    planetId: 69,
    name: "Ylir",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Home,
  },
  {
    systemId: 59,
    planetId: 70,
    name: "Archon Vail",
    resources: 1,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
    specialty: Specialty.Propulsion,
  },
  {
    systemId: 60,
    planetId: 71,
    name: "Perimeter",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 61,
    planetId: 72,
    name: "Ang",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Warfare,
  },
  {
    systemId: 62,
    planetId: 73,
    name: "Sem-Lore",
    resources: 3,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
    specialty: Specialty.Cybernetics,
  },
  {
    systemId: 63,
    planetId: 74,
    name: "Vorhal",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
    specialty: Specialty.Biotic,
  },
  {
    systemId: 64,
    planetId: 75,
    name: "Atlas",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 65,
    planetId: 76,
    name: "Primor",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Legendary,
    trait: Trait.Cultural,
  },
  {
    systemId: 66,
    planetId: 77,
    name: "Hope's End",
    resources: 3,
    influence: 0,
    planetType: PlanetType.Legendary,
    trait: Trait.Hazardous,
  },
  {
    systemId: 67,
    planetId: 78,
    name: "Cormund",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 68,
    planetId: 79,
    name: "Everra",
    resources: 3,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 69,
    planetId: 80,
    name: "Accoen",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 69,
    planetId: 81,
    name: "Jeol Ir",
    resources: 2,
    influence: 3,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 70,
    planetId: 82,
    name: "Kraag",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 70,
    planetId: 83,
    name: "Siig",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 71,
    planetId: 84,
    name: "Ba'Kal",
    resources: 3,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 71,
    planetId: 85,
    name: "Alio Prima",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 72,
    planetId: 86,
    name: "Lisis",
    resources: 2,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 72,
    planetId: 87,
    name: "Velnor",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Warfare,
  },
  {
    systemId: 73,
    planetId: 88,
    name: "Cealdri",
    resources: 0,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
    specialty: Specialty.Cybernetics,
  },
  {
    systemId: 73,
    planetId: 89,
    name: "Xanhact",
    resources: 0,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 74,
    planetId: 90,
    name: "Vega Major",
    resources: 2,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 74,
    planetId: 91,
    name: "Vega Minor",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
    specialty: Specialty.Propulsion,
  },
  {
    systemId: 75,
    planetId: 92,
    name: "Loki",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 75,
    planetId: 93,
    name: "Abaddon",
    resources: 1,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Cultural,
  },
  {
    systemId: 75,
    planetId: 94,
    name: "Ashtroth",
    resources: 2,
    influence: 0,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 76,
    planetId: 95,
    name: "Rigel I",
    resources: 0,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Hazardous,
  },
  {
    systemId: 76,
    planetId: 96,
    name: "Rigel II",
    resources: 1,
    influence: 2,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
  },
  {
    systemId: 76,
    planetId: 97,
    name: "Rigel III",
    resources: 1,
    influence: 1,
    planetType: PlanetType.Normal,
    trait: Trait.Industrial,
    specialty: Specialty.Biotic,
  },
  {
    systemId: 82,
    planetId: 98,
    name: "Mallice",
    resources: 0,
    influence: 3,
    planetType: PlanetType.Legendary,
    trait: Trait.Cultural,
  },
  {
    systemId: 83,
    planetId: 99,
    name: "Mallice",
    resources: 0,
    influence: 3,
    planetType: PlanetType.Legendary,
    trait: Trait.Cultural,
  },
];

const SystemData: System[] = [
  {
    systemId: 1,
    factionId: 6,
    name: "The Federation of Sol",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 2,
    factionId: 9,
    name: "The Mentak Coalition",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 3,
    factionId: 16,
    name: "The Yin Brotherhood",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 4,
    factionId: 4,
    name: "The Embers of Muaat",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 5,
    factionId: 1,
    name: "The Arborec",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 6,
    factionId: 8,
    name: "The L1Z1X Mindnet",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 7,
    factionId: 14,
    name: "The Winnu",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 8,
    factionId: 11,
    name: "The Nekro Virus",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 9,
    factionId: 10,
    name: "The Naalu Collective",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 10,
    factionId: 2,
    name: "The Barony of Letnev",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 11,
    factionId: 3,
    name: "The Clan of Saar",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 12,
    factionId: 13,
    name: "The Universities of Jol-Nar",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 13,
    factionId: 12,
    name: "Sardakk N'orr",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 14,
    factionId: 15,
    name: "The Xxcha Kingdom",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 15,
    factionId: 17,
    name: "The Yssaril Tribes",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 16,
    factionId: 5,
    name: "The Emirates of Hacan",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 17,
    factionId: 7,
    name: "The Ghosts of Creuss",
    game: Expansion.BaseGame,
    wormholes: [Wormhole.Delta],
    systemType: SystemType.Green,
    emptySystem: true,
    unique: UniqueTile.GhostsHomeSystem,
  },
  {
    systemId: 51,
    factionId: 7,
    name: "The Ghosts of Creuss",
    game: Expansion.BaseGame,
    wormholes: [Wormhole.Delta],
    systemType: SystemType.Green,
    emptySystem: false,
    unique: UniqueTile.GhostsSliceSystem,
  },
  {
    systemId: 52,
    factionId: 20,
    name: "The Mahact Gene-sorcerers",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 53,
    factionId: 22,
    name: "The Nomad",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 54,
    factionId: 24,
    name: "The Vuil'raith Cabal",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 55,
    factionId: 23,
    name: "The Titans of Ul",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 56,
    factionId: 19,
    name: "The Empyrean",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.Nebula,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 57,
    factionId: 21,
    name: "The Naaz-Rokha Alliance",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 58,
    factionId: 18,
    name: "The Argent Flight",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Green,
    emptySystem: false,
  },
  {
    systemId: 18,
    name: "Mecatol Rex",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
    unique: UniqueTile.MecatolRex,
  },
  {
    systemId: 19,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 20,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 21,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 22,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 23,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 24,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 25,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 26,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 27,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 28,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 29,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 30,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 31,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 32,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 33,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 34,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 35,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 36,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 37,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 38,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 39,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [Wormhole.Alpha],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 40,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [Wormhole.Beta],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 41,
    name: "",
    game: Expansion.BaseGame,
    anomaly: Anomaly.GravityRift,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 42,
    name: "",
    game: Expansion.BaseGame,
    anomaly: Anomaly.Nebula,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 43,
    name: "",
    game: Expansion.BaseGame,
    anomaly: Anomaly.Supernova,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 44,
    name: "",
    game: Expansion.BaseGame,
    anomaly: Anomaly.AsteroidField,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 45,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [Wormhole.Beta],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 46,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 47,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 48,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 49,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 50,
    name: "",
    game: Expansion.BaseGame,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 59,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 60,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 61,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 62,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 63,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 64,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 65,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
    unique: UniqueTile.Primor,
  },
  {
    systemId: 66,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
    unique: UniqueTile.HopesEnd,
  },
  {
    systemId: 67,
    name: "",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.GravityRift,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: false,
  },
  {
    systemId: 68,
    name: "",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.Nebula,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: false,
  },
  {
    systemId: 69,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 70,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 71,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 72,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 73,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 74,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 75,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 76,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Blue,
    emptySystem: false,
  },
  {
    systemId: 77,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 78,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 79,
    name: "",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.AsteroidField,
    wormholes: [Wormhole.Alpha],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 80,
    name: "",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.Supernova,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 81,
    name: "",
    game: Expansion.ProphecyOfKings,
    anomaly: Anomaly.MuaatSupernova,
    wormholes: [],
    systemType: SystemType.Red,
    emptySystem: true,
  },
  {
    systemId: 82,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [Wormhole.Gamma],
    systemType: SystemType.Blue,
    emptySystem: false,
    unique: UniqueTile.MalliceStartingSide,
  },
  {
    systemId: 83,
    name: "",
    game: Expansion.ProphecyOfKings,
    wormholes: [Wormhole.Alpha, Wormhole.Beta, Wormhole.Gamma],
    systemType: SystemType.Blue,
    emptySystem: false,
    unique: UniqueTile.MalliceFlippedSide,
  },
];

export { PlanetData };
